---
title: "INSTITUCIONAL"
description: |
  Armonización de Estadísticas Provinciales de Turismo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

*Armonización de las Estadísticas de Turismo en las Provincias* es un proyecto de la Dirección Nacional de Mercados y Estadística de la Subsecretaría de Desarrollo Estratégico del Ministerio de Turismo y Deportes.

El objetivo general es contribuir con propuestas metodológicas, capacitaciones y herramientas accesibles para los sistemas de estadísticas de turismo provinciales que orienten a producir indicadores provinciales básicos y comparables.

Además de este, se encuentran disponibles una serie de documentos técnicos que abordan otras problemáticas vinculadas a la producción de estadística de turismo:

**Documento Técnico \#1:** Conceptos y elementos básicos para la medición provincial de los turistas

**Documento Técnico \#2:** Propuestas metodológicas para las encuestas de ocupación en alojamientos turísticos

**Documento Técnico \#3**: Descripción, análisis y utilización de los Registros Administrativos para la medición del Turismo

**Documento Técnico \#4:** Propuestas Metodológicas para las Encuestas de Perfil del Visitante

Documento Técnico \#5: Medición de la contribución económica del turismo: actividad y empleo
