---
title: "ESTADÍSTICAS PROVINCIALES DE TURISMO"
description: |
 *Armonización de las Estadísticas de Turismo en las Provincias* es un proyecto de la Dirección Nacional de Mercados y Estadística de la [Subsecretaría de Turismo del Ministerio del Interior](https://www.argentina.gob.ar/interior/turismo){target="_blank"}.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

La finalidad del proyecto es contribuir al fortalecimiento de los sistemas de estadística provinciales con el objetivo de generar información robusta y confiable de la actividad turística de nuestro país.

Para ello, se elaboran propuestas y herramientas accesibles que permiten producir indicadores provinciales básicos y comparables en cuatro ejes: **(i)** actualización metodológica; **(ii)** capacitaciones; **(iii)** coordinación y gestión de datos; y **(iv)** espacios de colaboración e intercambio de experiencias.

------------------------------------------------------------------------

### Actualización Metodológica

En primer lugar, el proyecto contempla la reedición y revisión periódica de una serie de documentos técnicos que abordan otras problemáticas vinculadas a la producción de estadística de turismo:

[**Documento Técnico #1**](https://dnme-minturdep.github.io/DT1_medicion_turismo/): Conceptos y elementos básicos para la medición provincial de los turistas

[**Documento Técnico #2**](https://dnme-minturdep.github.io/DT2_encuestas/): Propuestas metodológicas para las encuestas de ocupación en alojamientos turísticos

[**Documento Técnico #3**](https://dnme-minturdep.github.io/DT3_registros_adminsitrativos/): Descripción, análisis y utilización de los Registros Administrativos para la medición del Turismo

[**Documento Técnico #4**](https://dnme-minturdep.github.io/DT4_perfiles/): Propuestas Metodológicas para las Encuestas de Perfil del Visitante

[**Documento Técnico \#**](https://dnme-minturdep.github.io/DT5_actividad_empleo/)**5**: Medición de la contribución económica del turismo: actividad y empleo

[**Documento Técnico #6**](https://dnme-minturdep.github.io/DT6_ciencia_de_datos_turismo/): Ciencia de Datos para el Turismo

Los **documentos metodológicos** buscan abordar las principales problemáticas a la hora de producir estadísticas de turismo sub-nacionales como también reforzar las definiciones y conceptos de turismo según las recomendaciones internacionales.

### Capacitaciones

En una segunda instancia, la capacitación de puntos focales de los gobiernos sub nacionales que tengan a cargo la administración, generación y/o análisis de estadísticas de turismo en sus respectivos distritos.

Las [**capacitaciones**](https://armonizacion.yvera.tur.ar/capacitaciones.html) pretenden fortalecer las capacidades de las y los referentes técnicos provinciales para poder mejorar la producción de estadísticas locales derivadas de los operativos de encuesta, explotación de registros administrativos y otras fuentes de información utilizadas.

### Sistema Federal de Gestión de Datos de Turismo

En paralelo, se desarrolla un sistema informático para ordenar, homogeneizar, jerarquizar y administrar  registros, operativos estadísticos y demás datos relativos al sector turístico de las distintas unidades administrativas.

Para ello, se trabaja para la construcción de un [**Sistema Federal de Gestión de Datos de Turismo (`<data>TUR`)**](https://datatur.yvera.tur.ar/), herramienta que tiene por objetivo facilitar el acopio y gestión de datos producidos por los diferentes organismos de turismo sub nacionales.

### Espacios de colaboración e intercambio

Con el fin de generar espacios de colaboración entre los distintos actores vinculados a la producción y explotación de las estadísticas de turismo, se gestiona también un [**foro permanente**](https://armonizacionespacio.slack.com/) ordenado en distintos canales temáticos que acompañan el contenido de este micrositio: documentos técnicos, bibliografía y trabajos de interés común.
